uart:
  id: "uart_bus"
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3

logger:
  baud_rate: 0

ht400:
  id: "ht400_id"

switch:
  - platform: "ht400"
    id: 'heater'
    name: "Heating"
  - platform: template
    name: "Modem Pairing"
    id: pairing
    optimistic: true
    on_turn_on:
      then:
        - lambda: 'id(ht400_id).pair();'
        - delay: 500ms
        - switch.turn_off: pairing

sensor:
  - platform: "ht400"
    id: 'room_temperature'
    name: "Room Temperature"
    accuracy_decimals: 2
    filters:
      - filter_out: 256.256
      - calibrate_linear:
        - 17.73 -> 7.65
        - 31.28 -> 21.81
      - median:
          window_size: 30
          send_every: 30
          send_first_at: 30

climate:
  - platform: thermostat
    name: "Room Thermostat"
    sensor: room_temperature
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 300s
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    preset:
      - name: Default
        default_target_temperature_low: 21.0

